apiVersion: v2
name: network-observability-operator
description: Helm chart for deploying the Network Observability Operator with Loki-backed flow storage
icon: https://raw.githubusercontent.com/openshift/console/master/frontend/public/imgs/logos/openshift.svg
home: https://rh-mobb.github.io/validated-pattern-helm-charts/
type: application
version: 2.1.3
appVersion: "1.11"
dependencies:
  - name: helper-status-checker
    version: 4.4.3
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
    condition: helper-status-checker.enabled
maintainers:
  - name: rh-mobb
