namespace: openshift-netobserv-operator

subscription:
  name: netobserv-operator
  channel: stable
  installPlanApproval: Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ""

operatorGroup:
  create: true

flowCollector:
  enabled: true
  namespace: netobserv
  deploymentModel: Direct
  agent:
    sampling: 50

helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: netobserv-operator
      subscriptionName: netobserv-operator
      namespace:
        name: openshift-netobserv-operator
      serviceAccount:
        name: "netobserv-install-check"
