{{- if .Values.certManagerRole }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    eks.amazonaws.com/role-arn: {{ .Values.certManagerRole }}
{{- end }}
