{{- if .Values.ambient.enabled }}
apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: {{ .Values.ambient.cni.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespace: {{ .Values.ambient.cni.namespace }}
  profile: ambient
  version: {{ .Values.ambient.cni.version | default .Values.ambient.version }}
  values:
    cni:
      ambient:
        reconcileIptablesOnStartup: true
{{- end }}
