{{ range $applications := .Values.applications }}
{{ if $applications.gitopsCreate }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $applications.apmnum }}-{{ $applications.appserviceNumber }}-team
  {{- if $applications.annotations }}
  annotations:
    {{- toYaml $applications.annotations | trimPrefix "|" | nindent 4 }}
  {{- end }}
  {{- if $applications.labels }}
  labels:
    {{- toYaml $applications.labels | trimPrefix "|" | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}