{{- if and .Values.lokiStack.enabled .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.lokiStack.storage.secretName }}
  namespace: {{ .Values.lokiStack.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.lokiStack.storage.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: audience
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: audience
    - secretKey: bucketnames
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: bucketnames
    - secretKey: region
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: region
    - secretKey: role_arn
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: role_arn
{{- end }}
