apiVersion: v2
name: mtv-operator
description: Helm chart for deploying Migration Toolkit for Virtualization (MTV) on OpenShift
type: application
version: 0.1.0
appVersion: "2.7"
dependencies:
  - name: helper-status-checker
    version: 4.4.3
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
home: https://rh-mobb.github.io/validated-pattern-helm-charts/
maintainers:
  - name: rh-mobb
