{{- if .Values.storageCluster.enabled }}
apiVersion: core.libopenstorage.org/v1
kind: StorageCluster
metadata:
  name: {{ .Values.storageCluster.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.storageCluster.syncWave | default "5" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Validate=false
    portworx.io/service-account: portworx
    {{- if .Values.storageCluster.smallNode }}
    portworx.io/misc-args: "-rt_opts small_conf=1"
    {{- end }}
spec:
  image: portworx/oci-monitor:{{ .Values.storageCluster.imageVersion }}
  imagePullPolicy: Always
  cloudStorage:
    deviceSpecs:
    {{- range .Values.storageCluster.cloudStorage.deviceSpecs }}
      - type={{ .type }},size={{ .size }},iops={{ .iops }}
    {{- end }}
    initialStorageNodes: {{ .Values.storageCluster.cloudStorage.initialStorageNodes }}
    kvdbDeviceSpec: {{ .Values.storageCluster.cloudStorage.kvdbDeviceSpec | quote }}
  secretsProvider: k8s
  stork:
    enabled: true
  autopilot:
    enabled: true
    providers:
      - name: default
        type: prometheus
        params:
          url: {{ .Values.storageCluster.autopilotPrometheusUrl | default "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091" }}
          tls-skip-verify: "true"
  {{- if .Values.storageCluster.iamRoleArn }}
  env:
    - name: PX_CLOUD_IDENTITY
      value: {{ .Values.storageCluster.iamRoleArn | quote }}
  workloadIdentity:
    credentials:
      - cloudProvider: aws
        key: eks.amazonaws.com/role-arn
        value: {{ .Values.storageCluster.iamRoleArn | quote }}
  {{- end }}
{{- end }}
