{{- if .Values.storageCluster.enabled }}
apiVersion: core.libopenstorage.org/v1
kind: StorageCluster
metadata:
  name: {{ .Values.storageCluster.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.storageCluster.syncWave | default "5" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Validate=false
    portworx.io/service-account: portworx
    portworx.io/service-type: "portworx-api:LoadBalancer"
    portworx.io/scc-priority: "11"
    {{- if .Values.storageCluster.smallNode }}
    portworx.io/misc-args: "-rt_opts small_conf=1"
    {{- end }}
spec:
  image: portworx/oci-monitor:{{ .Values.storageCluster.imageVersion }}
  imagePullPolicy: Always
  startPort: {{ .Values.storageCluster.startPort | default 17001 }}
  cloudStorage:
    deviceSpecs:
    {{- range .Values.storageCluster.cloudStorage.deviceSpecs }}
      - type={{ .type }},size={{ .size }},iops={{ .iops }}
    {{- end }}
    initialStorageNodes: {{ .Values.storageCluster.cloudStorage.initialStorageNodes }}
    kvdbDeviceSpec: {{ .Values.storageCluster.cloudStorage.kvdbDeviceSpec | quote }}
  secretsProvider: k8s
  monitoring:
    prometheus:
      enabled: false
      exportMetrics: true
      alertManager:
        enabled: false
  stork:
    enabled: true
  autopilot:
    enabled: {{ .Values.storageCluster.autopilot.enabled }}
    {{- if .Values.storageCluster.autopilot.enabled }}
    providers:
      - name: default
        type: prometheus
        params:
          url: {{ .Values.storageCluster.autopilot.prometheusUrl }}
    env:
      - name: SSL_CERT_DIR
        value: /etc/ssl/certs:/etc/ssl/custom
    volumes:
      - name: autopilot-service-ca
        mountPath: /etc/ssl/custom
        configMap:
          name: autopilot-service-ca
    {{- end }}
  {{- if .Values.storageCluster.iamRoleArn }}
  env:
    - name: PX_CLOUD_IDENTITY
      value: {{ .Values.storageCluster.iamRoleArn | quote }}
  workloadIdentity:
    credentials:
      - cloudProvider: aws
        key: eks.amazonaws.com/role-arn
        value: {{ .Values.storageCluster.iamRoleArn | quote }}
  {{- end }}
  {{- if .Values.storageCluster.ocpDynamicPlugin }}
  ocpDynamicPlugin:
    cacheAgentImage: {{ .Values.storageCluster.ocpDynamicPlugin.cacheAgentImage | quote }}
    pluginImage: {{ .Values.storageCluster.ocpDynamicPlugin.pluginImage | quote }}
  {{- end }}
{{- end }}
