{{ range $app := .Values.applications }}
{{ if $app.gitopsCreate }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $app.apmnum }}-{{ $app.appserviceNumber }}-team
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.gitopsNamespace }}
    {{- if $app.labels }}
    {{- toYaml $app.labels | nindent 4 }}
    {{- end }}
  {{- if $app.annotations }}
  annotations:
    {{- toYaml $app.annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
