namespace: portworx

subscription:
  name: portworx-certified
  channel: stable
  installPlanApproval: Manual
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ""

operatorGroup:
  create: true
  name: portworx-operator-group

storageCluster:
  enabled: true
  name: px-cluster-v3
  imageVersion: "3.6.1"
  startPort: 17001
  syncWave: 5
  miscArgs: "-rt_opts small_conf=1 -T px-storev2 "
  # Authentication: use iamRoleArn for IRSA, or awsCredsSecret for static keys
  iamRoleArn: ""
  # awsCredsSecret: "aws-creds"
  kvdb:
    enableTLS: false
  cloudStorage:
    deviceSpecs:
      - "type=gp3,size=50"
      - "type=gp3,size=50"
      - "type=gp3,size=50"
      - "type=gp3,size=50"
    journalDeviceSpec: "type=gp3,size=3"
    systemMetadataDeviceSpec: "type=gp3,size=64"
  runtimeOptions:
    default-io-profile: "6"
  autopilot:
    enabled: true
    prometheusUrl: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"
  ocpDynamicPlugin:
    cacheAgentImage: "docker.io/portworx/px-cache-agent:1.1.0-ea"
    pluginImage: "docker.io/portworx/portworx-dynamic-plugin:2.3.0-ea"

monitoring:
  enableUserWorkload: true

helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: portworx-operator
      subscriptionName: portworx-certified
      namespace:
        name: portworx
      sleeptimer: 10
      maxretries: 60
      serviceAccount:
        name: "portworx-status-checker"
