{{- if .Values.alertmanagerConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: {{ include "acm-observability.namespace" . }}
  labels:
    {{- include "acm-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  alertmanager.yaml: |
    {{- .Values.alertmanagerConfig.config | nindent 4 }}
{{- end }}
