{{- if .Values.objectStorage.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStorage.name }}
  namespace: {{ include "acm-observability.namespace" . }}
  labels:
    {{- include "acm-observability.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  {{ .Values.objectStorage.key }}: |
    {{- include "acm-observability.thanosObjectStorageConfig" . | nindent 4 }}
{{- end }}
