apiVersion: v2
name: overprovisioning
description: Overprovisioning DaemonSet to reserve spare capacity on every node
icon: https://raw.githubusercontent.com/openshift/console/master/frontend/public/imgs/logos/openshift.svg
type: application
version: 0.0.8
home: https://rh-mobb.github.io/validated-pattern-helm-charts/
maintainers:
  - name: rh-mobb
